version: '3.8'

services:
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.19.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    working_dir: /app/apps/web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped